name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read        
      id-token: write       
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.7"
      - run: python -m pip install --upgrade pip build
        name: Install build tool
      - run: python -m build
        name: Build distributions
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Upload distribution to PyPI
