name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.7"
      - name: Install build tool
        run: python -m pip install --upgrade pip build
      - name: Build distributions
        run: python -m build
      - name: Upload distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      
    permissions:
      contents: read
      id-token: write
